<?php

namespace Agregator\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CerereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CerereRepository extends EntityRepository
{
}