<?php

namespace Agregator\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends EntityRepository
{
    public function findAllByCategorySlug($slug)
    {
        $qb = $this->_em->createQueryBuilder();
        
        $qb ->select('partial o.{id, nume, descriere, slug}' )
            ->from('AgregatorFrontendBundle:Oferta', 'o')
            ->leftJoin('o.categorii', 'c')
            ->where("c.slug = '$slug'")
            ;
        
        $results = $qb->getQuery()->getArrayResult();
        
        return $results;
    }
}