parameters:
#    blogger_blog.example.class: Blogger\BlogBundle\Example
    blogger_blog.comments.latest_comment_limit: 10


services:
#    blogger_blog.example:
#        class: %blogger_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    blogger_blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
        tags:
            - { name: twig.extension }
